const express = require('express'); const multer = require('multer'); const path = require('path'); const fs = require('fs'); const axios = require('axios'); const db = require('./database'); const bot = require('./bot');
const router = express.Router(); const uploadDir = path.join(__dirname, '../uploads'); fs.mkdirSync(uploadDir, { recursive: true }); const upload = multer({ dest: uploadDir, limits: { fileSize: 50 * 1024 * 1024 } });
router.get('/users', (req, res) => res.json(db.users())); router.get('/users/:id', (req, res) => { const u = db.getUser(Number(req.params.id)); res.json(u || {}) }); router.get('/users/:id/messages', (req, res) => res.json(db.messages(Number(req.params.id)))); router.get('/stats', (req, res) => res.json(db.stats()));
router.post('/users/:id/block', (req, res) => res.json({ ok: !!db.setBlocked(Number(req.params.id), true) })); router.post('/users/:id/unblock', (req, res) => res.json({ ok: !!db.setBlocked(Number(req.params.id), false) }));
router.post('/send', upload.single('file'), async (req, res) => { try { const id = Number(req.body.userId), text = req.body.text || ''; if (!db.getUser(id)) return res.status(404).json({ ok: false, error: 'User topilmadi' }); if (req.file) { const mime = req.file.mimetype; const kind = mime.startsWith('image/') ? 'photo' : mime.startsWith('video/') ? 'video' : mime.startsWith('audio/') ? (mime.includes('ogg') ? 'voice' : 'audio') : 'document'; await bot.sendMedia(id, kind, req.file.path, text); db.addMessage({ user_id: id, from_type: 'admin', kind, text, file_name: req.file.originalname, mime_type: mime }); } else { if (!text.trim()) return res.status(400).json({ ok: false, error: 'Xabar bo‘sh' }); await bot.sendToUser(id, text); db.addMessage({ user_id: id, from_type: 'admin', kind: 'text', text }); } if (req.file) fs.unlink(req.file.path, () => { }); res.json({ ok: true }) } catch (e) { if (req.file) fs.unlink(req.file.path, () => { }); res.status(500).json({ ok: false, error: e.message }) } });
router.post('/broadcast', upload.single('file'), async (req, res) => { let sent = 0, failed = 0; const list = db.users().filter(u => !u.blocked); try { for (const u of list) { try { if (req.file) { const mime = req.file.mimetype; const kind = mime.startsWith('image/') ? 'photo' : mime.startsWith('video/') ? 'video' : mime.startsWith('audio/') ? (mime.includes('ogg') ? 'voice' : 'audio') : 'document'; await bot.sendMedia(u.id, kind, req.file.path, req.body.text || ''); } else await bot.sendToUser(u.id, req.body.text || ''); sent++; } catch { failed++ } await new Promise(r => setTimeout(r, 40)); } res.json({ ok: true, sent, failed, total: list.length }) } finally { if (req.file) fs.unlink(req.file.path, () => { }) } });
router.get('/search/music', async (req, res) => { try { const q = String(req.query.q || '').trim(); if (!q) return res.json({ results: [] }); const r = await axios.get('https://itunes.apple.com/search', { params: { term: q, media: 'music', entity: 'song', limit: 15 }, timeout: 10000 }); res.json({ results: r.data.results.map(x => ({ title: x.trackName, artist: x.artistName, album: x.collectionName, cover: x.artworkUrl100?.replace('100x100', '300x300'), preview: x.previewUrl, store: x.trackViewUrl })) }); } catch (e) { res.status(502).json({ error: 'Musiqa qidiruvi vaqtincha ishlamadi' }) } });
router.get('/search/video', async (req, res) => { const q = String(req.query.q || '').trim(); if (!q) return res.json({ results: [] }); if (process.env.YOUTUBE_API_KEY) { try { const r = await axios.get('https://www.googleapis.com/youtube/v3/search', { params: { part: 'snippet', q, type: 'video', maxResults: 15, key: process.env.YOUTUBE_API_KEY }, timeout: 10000 }); return res.json({ results: r.data.items.map(x => ({ title: x.snippet.title, channel: x.snippet.channelTitle, thumb: x.snippet.thumbnails?.medium?.url, url: `https://www.youtube.com/watch?v=${x.id.videoId}` })) }); } catch (e) { return res.status(502).json({ error: 'YouTube API xatosi' }) } } res.json({ results: [{ title: `YouTube’da “${q}” qidirish`, channel: 'YouTube', url: `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}` }], fallback: true }) });
module.exports = router;
